project_id = "awfyhgeflakjhxtntokd"

[functions.generate-blog-image]
verify_jwt = true

[functions.send-contact-message]
verify_jwt = false

[functions.send-pilot-application]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.notify-feature-request]
verify_jwt = false

[functions.hobson-chat]
verify_jwt = false

[functions.update-chatbot-knowledge]
verify_jwt = false

[functions.import-legacy-faqs]
verify_jwt = true

[functions.import-legacy-glossary]
verify_jwt = true

[functions.verify-investment-password]
verify_jwt = false

[functions.generate-investment-pdf]
verify_jwt = false

[functions.update-investment-password]
verify_jwt = true

[functions.store-reward-email]
verify_jwt = false

[functions.send-test-contact-email]
verify_jwt = true

[functions.send-test-pilot-email]
verify_jwt = true

[functions.upload-blog-images]
verify_jwt = true